### ISSUE TITLE
Getting error while following steps mentioned in Run It

### ISSUE THREAD

**Issue by BanamaliM** [dmh2000/node-oscope#1]
Hi,

I have downloaded the .zip file and followed all the steps that is mention in Run It to run the program.
But while performing step : "npm start", I am getting socket error.
A screen shot of the error is attached .Kindly help me in resolving the issue.

Thanks
![Uploading error.png…]()

**Comment by BanamaliM** [comment]
I think error screenshot is not attached:
Providing the error description:
$ npm start

> node-oscope@0.0.0 start c:\BanamaliM\ReST_Demo\node-oscope-master
> node node-oscope.js

http on : 3000
receiver : listening on port 55003
bound to 55003
c:\BanamaliM\ReST_Demo\node-oscope-master\lib\socket.js:36
    io.sockets.sockets.forEach(function(v,i,a) {
                       ^

TypeError: io.sockets.sockets.forEach is not a function
    at send (c:\BanamaliM\ReST_Demo\node-oscope-master\lib\socket.js:36:24)
    at Socket.<anonymous> (c:\BanamaliM\ReST_Demo\node-oscope-master\lib\receiver.js:76:7)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:480:8)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\
\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! node-oscope@0.0.0 start: `node node-oscope.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-oscope@0.0.0 start script 'node node-oscope.js'.
npm ERR! This is most likely a problem with the node-oscope package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node-oscope.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-oscope
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-oscope
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\BanamaliM\ReST_Demo\node-oscope-master\npm-debug.log

Thank you.

**Comment by dmh2000** [comment]
Hi it's probably a version mismatch with socketio since the code is a bit
old. I will update it but it will be 2 weeks until I can do it. Sorry for
the delay. Thanks for downloading.
